---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.3.3.0

branches:
  only:
    - master

script:
  # Check the playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
