---
- name: Add an apt signing key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
    state: present

- name: Install required packages
  apt:
    name: docker-ce
    update_cache: yes
    state: present

- name: Download docker-compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VER }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: "{{ DOCKER_COMPOSE_FILE }}"
    mode: 0755
